name: CI on Push and Pull Request

on: [push, pull_request]

jobs:
  Practice:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo LiLo.Lite
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Show what's in the directory
      run: |
        ls
    - name: Show what all is in the parent directory
      run: |
        cd ..
        ls
        
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        cd LiLo.Lite
        nuget restore
        cd LiLo.Lite.Android
        msbuild LiLo.Lite.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        cd LiLo.Lite
        nuget restore
        msbuild LiLo.Lite.iOS/LiLo.Lite.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug